### ISSUE TITLE
Please add a link

### ISSUE THREAD

**Issue by frnhr** [grnhse/greenhouse-api-docs#12]
In https://github.com/grnhse/greenhouse-api-docs/blob/master/source/includes/job-board/_applications.md 

> In general, we would encourage customers to make use of the Embedded Job Application before going to...

A link to documentation about this `Embedded Job Application` feature would be most useful here.

**Comment by capablemonkey** [comment]
Hi @frnhr!  Sorry for the very late reply.  I agree with your suggestion 100%.  It's in our backlog to re-write the existing Embedded Job Application (this is feature which lets you easily embed a Greenhouse-hosted job board or application as an iframe) documentation on this developer portal.   

In the meantime, you can find documentation (which includes step by step guides) in Greenhouse under the Dev Center configuration page.  Since it requires a Greenhouse user account with the appropriate permissions to access this page, we figured it would be confusing to link to it from our public API docs.

Once we've re-written the docs, I'll be sure to address this issue.

Thanks for the suggestion!  :)
