### ISSUE TITLE
CORS on jobs POST

### ISSUE THREAD

**Issue by robsterlini** [grnhse/greenhouse-api-docs#236]
Both locally and on a development server hosted on Netlify, I get a CORS rejection for a `POST` request to `https://developers.greenhouse.io/job-board.html#submit-an-application`. Is there a way to set the accepted URLs?

**Comment by rachelleffel** [comment]
Hi @robsterlini,

You will get a CORS error if you attempt to post to the API from the browser. Because POST requests require the use of an API Key, which must be kept secret, we do not allow browser requests to the POST Applications endpoint, and all POST requests must be made from the server-side. If you have any questions about this, please send an email with the relevant details to support@greenhouse.io.
