### ISSUE TITLE
No "page" query string parameter in GET: List EEOC 

### ISSUE THREAD

**Issue by tplassart** [grnhse/greenhouse-api-docs#287]
Hello,

There is a **"per_page"** query string parameter for `GET: List EEOC` but no **"page"** parameter so if there are more than 500 lines, it is not possible to get all of them.

Is it intended ? 

Thank you !

**Comment by tdphillipsjr** [comment]
Hello,

The EEOC endpoint has very few options. It is intended for this endpoint to not have paging as we do not expect for it to ever have enough options to require them to be paged.

- Tom

**Comment by tdphillipsjr** [comment]
Hello again - I'm sorry, but I was incorrect in my first response. I was thinking of the other EEOC endpoint.

The correct answer to your question is that we use a different paging mechanism for this endpoint than the other endpoints. Because of the volume of data in this endpoint, it does not support random access paging. The Link header returned in a successful request supplies a link to the next page with a `since_id`; this will give you the next 500 records. For example: 

`***Link →<https://harvest.greenhouse.io/v1/eeoc?per_page=100&since_id=102717457>; rel="next"***`

This would give you the next 100 records starting with the ID 102717457.

See the "Pagination" section of the documentation and the paragraph that starts with `As of February 2017,`

I apologize for the previous incorrect response.
