### ISSUE TITLE
Example request for Job Board API

### ISSUE THREAD

**Issue by gertig** [grnhse/greenhouse-api-docs#7]
Would it be possible to have an example curl request for applying to a job via the Job Board API? I keep running into:

````
{
    "error": "Failed to save person",
    "status": 401
}
````

**Comment by rachelleffel** [comment]
Hi Andrew,

That's definitely something we're looking to do! Here is an example request that you can work off of for now:

```
curl -X POST -H "Authorization: Basic BASE64-ENCODED API KEY" -H "Cache-Control: no-cache" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "first_name=example" -F "last_name=example" -F "id=00000" -F "email=example@example.com" -F "resume=@test_resume.pdf" "https://api.greenhouse.io/v1/applications/"
```

If that isn't working for you, you can reach out to tech-support@greenhouse.io, and we'll take a look at the request you're sending!

**Comment by rafaelramalho19** [comment]
How was this fixed? I'm having the exact same problem.

**Comment by robsterlini** [comment]
Any chance that the error handling could be changed to be a bit more informative? Getting `Failed to save person` for every request makes it impossible to debug what is causing the issue.

**Comment by gertig** [comment]
It has been a little while since I’ve dealt with this issue, but if I recall correctly my problem was that I was not passing an email when attempting to save.

**Comment by rachelleffel** [comment]
@robsterlini We've just released an update to this API to return more specific error messages when the POST request fails. I hope that helps!

**Comment by fpozzobon** [comment]
Hi @rachelleffel, we are also facing `"status":400,"error":"Failed to save person"` from time to time...
Any idea what could be the cause ? Is there some logs available on Greenhouse to have a more insight on that ?

**Comment by darkbluetech** [comment]
Any update on this issue? 

I'm getting `"status":400,"error":"Failed to save person"` with seemingly nothing wrong.

This issue should be re-opened, it hasn't been fixed.

**Comment by rachelleffel** [comment]
@fpozzobon and @darkbluetech 

The API will return that error if there is an issue with the body of your request, which could be a problem specific to your request syntax, or with the job post that you have configured in Greenhouse. In order to get specific information to help you determine what the issue is, I recommend contacting the Greenhouse Support team here: https://support.greenhouse.io/hc/en-us/requests/new

Please include the details of a request you've submitted (with the API Key redacted) and the error you've received, and our Support team would be happy to help investigate.
